spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lab5
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    path: /error

